name: PR

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install jsonnet
        run: |
          mkdir jsonnet
          curl -o jsonnet.tar.gz -L https://github.com/google/jsonnet/releases/download/v0.14.0/jsonnet-bin-v0.14.0-linux.tar.gz
          tar -xzf jsonnet.tar.gz -C jsonnet
          echo "::add-path::jsonnet"
      - name: Lint jsonnet
        run: make lint-jsonnet
      - name: Build schemas
        run: make build-schemas
      - name: Archive schema artifacts
        uses: actions/upload-artifact@v1
        with:
          name: schemas
          path: schemas
  upload-schemas-to-gcs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download built schemas
        uses: actions/download-artifact@v1
        with:
          name: schemas
      - name: GCS
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - run: gcloud info
  test-translation-templates:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download built schemas
        uses: actions/download-artifact@v1
        with:
          name: schemas
      - name: Install pipenv
        run: pip install pipenv==2018.11.26
      - run: |
          ls
      - name: Cache virtualenv
        id: cache-virtualenv
        uses: actions/cache@v1
        with:
            path: ~/.local/share/virtualenvs/
            key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-virtualenvs-${{ hashFiles('Pipfile.lock') }}
      - name: Install virtual environment
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: pipenv install --dev
      - name: Test translation templates
        run: make test-translation-templates
  validate-schemas:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download built schemas
        uses: actions/download-artifact@v1
        with:
          name: schemas
      - run: make run-validator
      - name: Validate schemas
        run: make validate-schemas
